dependencies:
  pre:
    - pip install codecov
    - git clone https://github.com/DLRSP/example -b django-sp
test:
  override:
    - coverage run example/manage.py test --exe --all-modules
post:
    - coverage html -d $CIRCLE_ARTIFACTS
    - codecov

