sudo: false
language: python
matrix:
  allow_failures:
    - os: osx
    - env: DJANGO_VERSION=3.0.2
os:
  - linux
  - osx
env:
  - DJANGO_VERSION=2.2.9
  - DJANGO_VERSION=3.0.2
python:
  - '3.6'
  - '3.7'
  - '3.8'
deploy:
  provider: pypi
  user: django-errors
  password:
    secure: ih7b2WOdCSMqiQ1gNj+I+s622ZhZgRafep3Obl92wB1kzK33Dcn3UYhPye7/Kx/HrC+rezY8xc51vUoTev65tc0UIafERUAHUiLBqVOsWZMCQ31gLxsAiPCM4pDFb9Zso9t7sn/smlwFQ/wBXbNUt/1g3U0uUvOEHqsoxZChpB4QLd1JLjJ0HFD8P0EPsYNEEIfkhswJqW0YxBoEg3k9nQXgdkWh+aMDVS7jLZzcSfvrjz9I9RtLq9MZ2OiTKlh7oQUnY9RRwxFCLXPNb+Ngd0iQClWXEY4ll8ddW9MtoepX6/+yfB9pmRHE2pEASv1QGitn3LGZQUCahiVCeaUzdoMfW5NIVEgWsHypgODVOFoWBjfgMTQqcRpxi9HiBCd934/TFaf0D8+OdJMzaTb4YgYDSG2YbIZz2aVTPwtskIc4AkSejQC31jXpiH0OAMSn+zc+veKM7zC32AXy8jUBhYjmxhmJCE2Chk6sL9DWysZgAkG6jN7eU4dcffXiH+rl1hpkkQHcDhIZn64O0teK9j3fFi4L/q2RGOGtHvMGKcw964U+BWsYKO+/YYJ0TP9oOK6sH7FJUc1DnyFzUBoOsEy34JPfqV763dmrwHyDBCogMfwLiE/O9sjx6TaHY+6DMubaiS/3YOeye2IQCQJm/NFP60h37BcTGUjXXa4UhRA=
  on:
    tags: true
    repo: DLRSP/django-errors
before_install:
  - pip install virtualenv
  - pip install codecov
install:
  - git clone --depth=50 --branch=django-errors https://github.com/DLRSP/example.git DLRSP/example
  - python setup.py install
script:
  - coverage run DLRSP/example/manage.py test --exe --all-modules
after_success:
  - codecov
