sudo: false
language: python
matrix:
  allow_failures:
    - os: osx
    - env: DJANGO_VERSION=3.0.2
os:
  - linux
  - osx
env:
  - DJANGO_VERSION=2.2.9
  - DJANGO_VERSION=3.0.2
python:
  - '3.6'
  - '3.7'
  - '3.8'
deploy:
  provider: pypi
  user: "dlrsp"
  password:
    secure: "YUWuABDgfA7e1LpVJJ+FsYfw982p2UQTYCB1hTsErs+c7AYF8JvydF/fPuJ1CHRluU4KSvETpyP6ZaGY6yj+ZwnHvy1RguGdds8afLVY+fEKgHzZzcGN6gJeXMCaigmjE87KP3/sSdUVEw18GwoPXT+bzCg/vykzhZe/D1yz4lTs73WClR834vFjenkJKJImraVAC9+/OqdAPRzv0qsMklpQKAirETuZKYSQ2+koRj/VWW1kEP0q5TFKjM7FyTkoGQmRHv4HNr96YSeKpKjSbOFzEQbHE1NLqA9tpXxqIOkGXIHBuwRl/akWn/OfVdkX23nk7ZYAakV4CYSiQRyhdOUT9HXQbmSqAc6sX/205VDJEA7cMD7jkD4UXaSvW13djFcOybMjVasWKvERNi8OGYaePHbZfWmsvW2bd9mRq7D9wNKyNLe371OnMjVGs2xQn1Q9jT/RLva971/sfnOB+KssYePqTN6pBi+/v28uFPzR2SRzN4IF7BSyZfeWHlvY1446dKwrhSubU16uidJXIRG0vNtE/Z+wY2L84x4VChLlSVcuOHDsANDbWUW+YmfykYrDT1redg61thcXff5M0nm5xZ9KOyuPp1H5EtLVMIfZek7+PwZ82TlTjOrwNsrhUHEOBzyexvZf8dV0Qr+BnVQXqbTvBTi4xkn23vUMnoc="
  on:
    tags: true
    repo: DLRSP/django-errors
before_install:
  - pip install virtualenv
  - pip install codecov
install:
  - git clone --depth=50 --branch=django-errors https://github.com/DLRSP/example.git DLRSP/example
  - python setup.py install
script:
  - coverage run DLRSP/example/manage.py test --exe --all-modules
after_success:
  - codecov
