---
name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  docs:
    uses: DLRSP/workflows/.github/workflows/docs.yaml@v1.8.12
    secrets: inherit
