name: Auto label merge conflicts

permissions:
  issues: write
  pull-requests: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  label-merge-conflicts:
    if: github.repository_owner == 'DLRSP'
    runs-on: ubuntu-latest
    steps:
      - uses: pradyunsg/auto-label-merge-conflicts@v3
        with:
          CONFLICT_LABEL_NAME: "needs rebase or merge"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
