---
name: Upgrade dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  upgrade:
    uses: DLRSP/workflows/.github/workflows/upgrade-dependency.yaml@main
    secrets: inherit
